### ISSUE TITLE
panic: no Auth Provider found for name "azure"

### ISSUE THREAD

**Issue by sossickd** [devtron-labs/silver-surfer#10]
Error running kubedd against an AKS 1.19 cluster.

```
kubedd --version
Version: 0.1.1
Commit: be36bb09c495cafd27b8f24d758f4e2c339c976b
Date: 2021-09-28T12:18:51Z

 kubedd --target-kubernetes-version 1.22
panic: no Auth Provider found for name "azure"

goroutine 1 [running]:
github.com/devtron-labs/silver-surfer/pkg.NewCluster(0x0, 0x0, 0x0, 0x0, 0x1ea6e05)
	/Users/pghildiy/go/src/github.com/devtron-labs/silver-surfer/pkg/Cluster.go:51 +0x3d4
main.processCluster(0x228ec99)
	/Users/pghildiy/go/src/github.com/devtron-labs/silver-surfer/main.go:167 +0xb5
main.glob..func1(0x2d66f00, 0xc0003b2780, 0x0, 0x2)
	/Users/pghildiy/go/src/github.com/devtron-labs/silver-surfer/main.go:108 +0x10c
github.com/spf13/cobra.(*Command).execute(0x2d66f00, 0xc000104190, 0x2, 0x2, 0x2d66f00, 0xc000104190)
	/Users/pghildiy/go/src/github.com/devtron-labs/silver-surfer/vendor/github.com/spf13/cobra/command.go:766 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2d66f00, 0x1005fa5, 0xc000100058, 0x0)
	/Users/pghildiy/go/src/github.com/devtron-labs/silver-surfer/vendor/github.com/spf13/cobra/command.go:852 +0x2fe
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/pghildiy/go/src/github.com/devtron-labs/silver-surfer/vendor/github.com/spf13/cobra/command.go:800
main.Execute()
	/Users/pghildiy/go/src/github.com/devtron-labs/silver-surfer/mai:258 +0x31
main.main()
	/Users/pghildiy/go/src/github.com/devtron-labs/silver-surfer/main.go:286 +0x25
```

**Comment by langburd** [comment]
The same error when using 'oidc' (through Dex) 
```
$ ./kubedd --version
Version: 0.1.1
Commit: be36bb09c495cafd27b8f24d758f4e2c339c976b
Date: 2021-09-28T12:18:51Z

$ ./kubedd --kubecontext some_oidc_context
panic: no Auth Provider found for name "oidc"

goroutine 1 [running]:
github.com/devtron-labs/silver-surfer/pkg.NewCluster(0x0, 0x0, 0x7ffeefbff89f, 0xc, 0x1ea6e05)
	/Users/pghildiy/go/src/github.com/devtron-labs/silver-surfer/pkg/Cluster.go:51 +0x3d4
main.processCluster(0x228ec99)
	/Users/pghildiy/go/src/github.com/devtron-labs/silver-surfer/main.go:167 +0xb5
main.glob..func1(0x2d66f00, 0xc00043a780, 0x0, 0x2)
	/Users/pghildiy/go/src/github.com/devtron-labs/silver-surfer/main.go:108 +0x10c
github.com/spf13/cobra.(*Command).execute(0x2d66f00, 0xc000112190, 0x2, 0x2, 0x2d66f00, 0xc000112190)
	/Users/pghildiy/go/src/github.com/devtron-labs/silver-surfer/vendor/github.com/spf13/cobra/command.go:766 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2d66f00, 0x1005fa5, 0xc00010e058, 0x0)
	/Users/pghildiy/go/src/github.com/devtron-labs/silver-surfer/vendor/github.com/spf13/cobra/command.go:852 +0x2fe
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/pghildiy/go/src/github.com/devtron-labs/silver-surfer/vendor/github.com/spf13/cobra/command.go:800
main.Execute()
	/Users/pghildiy/go/src/github.com/devtron-labs/silver-surfer/main.go:258 +0x31
main.main()
	/Users/pghildiy/go/src/github.com/devtron-labs/silver-surfer/main.go:286 +0x25
```
The example of `kubeconfig` configuration:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJT...
    server: https://masters.fqdn:6443
  name: some_oidc_context
contexts:
- context:
    cluster: some_oidc_context
    user: user@some_oidc_context
  name: some_oidc_context
current-context: some_oidc_context
kind: Config
preferences: {}
users:
- name: user@some_oidc_context
  user:
    auth-provider:
      config:
        client-id: kubectl
        client-secret: kubectl
        extra-scopes: offline_access openid profile email groups
        id-token: eyJhbGciOiJS...
        idp-certificate-authority-data: LS0tLS1CRUd...
        idp-issuer-url: https://masters.fqdn:32000/dex
        refresh-token: ChlvZmVtZm...
      name: oidc

```
