### ISSUE TITLE
False positive for API deprecation 1.16 for field last-applied-configuration even when apiVersion is correctly set

### ISSUE THREAD

**Issue by rootnoir** [devtron-labs/silver-surfer#25]
The apiVersion is clearly set as `apps/v1`, however in the **last-applied-configuration** field there is a mention of `extensions/v1beta1`. The deployment is listed by `kubedd` as having the deprecation.

Example:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "37"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment" ........
```
