### ISSUE TITLE
False positive for API deprecation 1.24 for field last-applied-configuration

### ISSUE THREAD

**Issue by BJKupka** [devtron-labs/silver-surfer#30]
I pulled the [latest release version](https://github.com/devtron-labs/silver-surfer/releases/tag/v0.1.1) of `silver-surfer` as of creation of this issue, installed and ran according to the documentation called out in the README, and witnessed that the report being generated called out one of our daemonset resources on some clusters are using a deprecated version:

```
Results for cluster at version 1.24+ to 1.24
-------------------------------------------
>>>> Removed API Version's <<<<
 Namespace    Name                     Kind                 API Version (Current Available)     Replace With API Version (Latest Available)   Migration Status                             
 monitoring   node-exporter            DaemonSet            apps/v1beta2                        apps/v1                                       can be migrated with just apiVersion change  
```

I combed through the configuration and found that both the current `apiVersion` and the `last-applied-configuration` reference the latest available version that the report calls out:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "35"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"node-exporter"},"name":"node-exporter","namespace":"monitoring"}
```

I'm trying to understand if this is a true false-positive situation or if there is something wrong on my end. Any advice/help would be greatly appreciated!

I read through all of your current and prior issues and what I am running into is, in my eyes, distinctly different from https://github.com/devtron-labs/silver-surfer/issues/25. Apologies if you feel that this is a duplicate of that issue.
